version: v2.1.6
plugins:
  # a plugin from a Go proxy
  - module: "github.com/manuelarte/presentation-golangci-lint"
    import: "github.com/manuelarte/presentation-golangci-lint/unexportedconstantscheck"
    version: latest
